[2025-05-21T07:52:17.885+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: aircraft_alerts_telegram.send_telegram_alerts manual__2025-05-21T07:52:16.594108+00:00 [queued]>
[2025-05-21T07:52:17.890+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: aircraft_alerts_telegram.send_telegram_alerts manual__2025-05-21T07:52:16.594108+00:00 [queued]>
[2025-05-21T07:52:17.892+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-05-21T07:52:17.900+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): send_telegram_alerts> on 2025-05-21 07:52:16.594108+00:00
[2025-05-21T07:52:17.906+0000] {standard_task_runner.py:57} INFO - Started process 376 to run task
[2025-05-21T07:52:17.910+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'aircraft_alerts_telegram', 'send_telegram_alerts', 'manual__2025-05-21T07:52:16.594108+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/aircraft_alerts_telegram.py', '--cfg-path', '/tmp/tmpqu3py9hi']
[2025-05-21T07:52:17.915+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask send_telegram_alerts
[2025-05-21T07:52:17.932+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-21T07:52:17.956+0000] {task_command.py:416} INFO - Running <TaskInstance: aircraft_alerts_telegram.send_telegram_alerts manual__2025-05-21T07:52:16.594108+00:00 [running]> on host 8b20e5ff94cb
[2025-05-21T07:52:18.009+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='aircraft_alerts_telegram' AIRFLOW_CTX_TASK_ID='send_telegram_alerts' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T07:52:16.594108+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-21T07:52:16.594108+00:00'
[2025-05-21T07:52:18.012+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-05-21T07:52:18.013+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:52:18.013+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:52:18.013+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-05-21T07:52:18.013+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:52:18.013+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:52:18.014+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.04 secs
[2025-05-21T07:52:18.063+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-05-21T07:52:18.063+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:52:18.063+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:52:18.064+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-05-21T07:52:18.064+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:52:18.064+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:52:18.064+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.12 secs
[2025-05-21T07:52:18.185+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-05-21T07:52:18.185+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:52:18.185+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:52:18.186+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-05-21T07:52:18.186+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:52:18.186+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:52:18.187+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.24 secs
[2025-05-21T07:52:18.429+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-05-21T07:52:18.431+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:52:18.432+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:52:18.433+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-05-21T07:52:18.433+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:52:18.434+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:52:18.434+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.48 secs
[2025-05-21T07:52:18.916+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-05-21T07:52:18.918+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:52:18.919+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:52:18.920+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-05-21T07:52:18.920+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:52:18.921+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:52:18.921+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.89 secs
[2025-05-21T07:52:19.810+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-05-21T07:52:19.810+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:52:19.810+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:52:19.811+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-05-21T07:52:19.811+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-21T07:52:19.811+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-21T07:52:19.811+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.20 secs
[2025-05-21T07:52:20.016+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/aircraft_alerts_telegram.py", line 19, in alert_unusual_aircraft
    consumer = KafkaConsumer(
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/consumer/group.py", line 387, in __init__
    self._client = self.config['kafka_client'](metrics=self._metrics, **self.config)
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 262, in __init__
    self.config['api_version'] = self.check_version()
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 1074, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-05-21T07:52:20.023+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=aircraft_alerts_telegram, task_id=send_telegram_alerts, execution_date=20250521T075216, start_date=20250521T075217, end_date=20250521T075220
[2025-05-21T07:52:20.031+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task send_telegram_alerts (NoBrokersAvailable; 376)
[2025-05-21T07:52:20.059+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-21T07:52:20.073+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
