[2025-05-20T11:36:38.677+0000] {processor.py:157} INFO - Started process (PID=169) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:36:38.677+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T11:36:38.678+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:36:38.678+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:36:38.693+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:36:38.689+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_to_snowflake.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-05-20T11:36:38.693+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:36:38.717+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.044 seconds
[2025-05-20T11:37:08.941+0000] {processor.py:157} INFO - Started process (PID=174) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:37:08.941+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T11:37:08.942+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:37:08.942+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:37:08.947+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:37:08.946+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_to_snowflake.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-05-20T11:37:08.947+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:37:08.959+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.021 seconds
[2025-05-20T11:37:39.238+0000] {processor.py:157} INFO - Started process (PID=179) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:37:39.239+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T11:37:39.240+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:37:39.239+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:37:39.250+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:37:39.248+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_to_snowflake.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-05-20T11:37:39.250+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:37:39.269+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.035 seconds
[2025-05-20T11:38:09.535+0000] {processor.py:157} INFO - Started process (PID=184) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:38:09.537+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T11:38:09.538+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:38:09.538+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:38:09.548+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:38:09.547+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_to_snowflake.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-05-20T11:38:09.548+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:38:09.572+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.041 seconds
[2025-05-20T11:38:39.854+0000] {processor.py:157} INFO - Started process (PID=189) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:38:39.855+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T11:38:39.857+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:38:39.856+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:38:39.872+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:38:39.870+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_to_snowflake.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-05-20T11:38:39.872+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:38:39.901+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.053 seconds
[2025-05-20T11:39:10.162+0000] {processor.py:157} INFO - Started process (PID=194) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:39:10.163+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T11:39:10.164+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:39:10.164+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:39:10.171+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:39:10.169+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_to_snowflake.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-05-20T11:39:10.171+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:39:10.189+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.029 seconds
[2025-05-20T11:39:40.486+0000] {processor.py:157} INFO - Started process (PID=199) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:39:40.488+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T11:39:40.489+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:39:40.488+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:39:40.498+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:39:40.496+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_to_snowflake.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-05-20T11:39:40.498+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:39:40.527+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.044 seconds
[2025-05-20T11:40:10.811+0000] {processor.py:157} INFO - Started process (PID=204) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:40:10.812+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T11:40:10.812+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:40:10.812+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:40:10.818+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:40:10.817+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_to_snowflake.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-05-20T11:40:10.818+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:40:10.833+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.023 seconds
[2025-05-20T11:40:41.224+0000] {processor.py:157} INFO - Started process (PID=209) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:40:41.228+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T11:40:41.229+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:40:41.229+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:40:41.237+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:40:41.236+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_to_snowflake.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-05-20T11:40:41.237+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:40:41.268+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.047 seconds
[2025-05-20T11:41:11.563+0000] {processor.py:157} INFO - Started process (PID=214) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:41:11.565+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T11:41:11.565+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:41:11.565+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:41:11.572+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:41:11.570+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_to_snowflake.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-05-20T11:41:11.572+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:41:11.591+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.031 seconds
[2025-05-20T11:41:41.961+0000] {processor.py:157} INFO - Started process (PID=219) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:41:41.963+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T11:41:41.967+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:41:41.965+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:41:41.986+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:41:41.983+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_to_snowflake.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-05-20T11:41:41.986+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:41:42.015+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.058 seconds
[2025-05-20T11:42:12.342+0000] {processor.py:157} INFO - Started process (PID=224) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:42:12.343+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T11:42:12.345+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:42:12.344+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:42:12.354+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:42:12.352+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_to_snowflake.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-05-20T11:42:12.354+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:42:12.380+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.043 seconds
[2025-05-20T11:42:42.685+0000] {processor.py:157} INFO - Started process (PID=229) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:42:42.687+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T11:42:42.689+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:42:42.688+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:42:42.696+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:42:42.694+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_to_snowflake.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-05-20T11:42:42.696+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:42:42.725+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.044 seconds
[2025-05-20T11:43:13.038+0000] {processor.py:157} INFO - Started process (PID=234) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:43:13.039+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T11:43:13.040+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:43:13.040+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:43:13.048+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:43:13.047+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_to_snowflake.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-05-20T11:43:13.049+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:43:13.072+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.040 seconds
[2025-05-20T11:43:43.471+0000] {processor.py:157} INFO - Started process (PID=239) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:43:43.474+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T11:43:43.475+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:43:43.475+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:43:43.489+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:43:43.487+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_to_snowflake.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-05-20T11:43:43.490+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:43:43.533+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.068 seconds
[2025-05-20T11:44:13.885+0000] {processor.py:157} INFO - Started process (PID=244) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:44:13.887+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T11:44:13.889+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:44:13.888+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:44:13.902+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:44:13.900+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_to_snowflake.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-05-20T11:44:13.902+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:44:13.946+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.065 seconds
[2025-05-20T11:44:44.200+0000] {processor.py:157} INFO - Started process (PID=249) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:44:44.202+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T11:44:44.204+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:44:44.203+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:44:44.213+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:44:44.211+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_to_snowflake.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-05-20T11:44:44.213+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:44:44.250+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.054 seconds
[2025-05-20T11:45:14.539+0000] {processor.py:157} INFO - Started process (PID=254) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:45:14.541+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T11:45:14.542+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:45:14.542+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:45:14.552+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:45:14.550+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_to_snowflake.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-05-20T11:45:14.552+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:45:14.580+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.048 seconds
[2025-05-20T11:45:44.878+0000] {processor.py:157} INFO - Started process (PID=259) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:45:44.880+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T11:45:44.882+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:45:44.881+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:45:44.893+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:45:44.890+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_to_snowflake.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-05-20T11:45:44.893+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:45:44.925+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.055 seconds
[2025-05-20T11:46:15.142+0000] {processor.py:157} INFO - Started process (PID=264) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:46:15.144+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T11:46:15.145+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:46:15.145+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:46:15.154+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:46:15.152+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_to_snowflake.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-05-20T11:46:15.154+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:46:15.179+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.042 seconds
[2025-05-20T11:46:45.545+0000] {processor.py:157} INFO - Started process (PID=269) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:46:45.547+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T11:46:45.549+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:46:45.548+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:46:45.561+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:46:45.559+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_to_snowflake.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-05-20T11:46:45.561+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:46:45.594+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.057 seconds
[2025-05-20T11:47:15.928+0000] {processor.py:157} INFO - Started process (PID=274) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:47:15.929+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T11:47:15.930+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:47:15.930+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:47:15.938+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:47:15.936+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_to_snowflake.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-05-20T11:47:15.938+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:47:15.959+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.037 seconds
[2025-05-20T11:47:46.281+0000] {processor.py:157} INFO - Started process (PID=279) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:47:46.284+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T11:47:46.285+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:47:46.284+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:47:46.293+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:47:46.291+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_to_snowflake.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-05-20T11:47:46.293+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:47:46.326+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.051 seconds
[2025-05-20T11:48:16.603+0000] {processor.py:157} INFO - Started process (PID=284) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:48:16.606+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T11:48:16.607+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:48:16.606+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:48:16.621+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:48:16.618+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_to_snowflake.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-05-20T11:48:16.621+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:48:16.657+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.060 seconds
[2025-05-20T11:48:46.975+0000] {processor.py:157} INFO - Started process (PID=289) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:48:46.978+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T11:48:46.979+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:48:46.979+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:48:46.988+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:48:46.986+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_to_snowflake.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-05-20T11:48:46.989+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:48:47.032+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.064 seconds
[2025-05-20T11:49:17.273+0000] {processor.py:157} INFO - Started process (PID=294) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:49:17.275+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T11:49:17.275+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:49:17.275+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:49:17.282+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:49:17.281+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_to_snowflake.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-05-20T11:49:17.283+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:49:17.311+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.043 seconds
[2025-05-20T11:49:47.654+0000] {processor.py:157} INFO - Started process (PID=299) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:49:47.656+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T11:49:47.657+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:49:47.656+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:49:47.669+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:49:47.667+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_to_snowflake.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-05-20T11:49:47.669+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:49:47.700+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.052 seconds
[2025-05-20T11:50:17.982+0000] {processor.py:157} INFO - Started process (PID=304) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:50:17.983+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T11:50:17.985+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:50:17.984+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:50:17.991+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:50:17.990+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_to_snowflake.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-05-20T11:50:17.991+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:50:18.007+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.029 seconds
[2025-05-20T11:50:48.281+0000] {processor.py:157} INFO - Started process (PID=309) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:50:48.283+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T11:50:48.284+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:50:48.283+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:50:48.295+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:50:48.293+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_to_snowflake.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-05-20T11:50:48.295+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:50:48.328+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.056 seconds
[2025-05-20T11:51:18.567+0000] {processor.py:157} INFO - Started process (PID=314) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:51:18.569+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T11:51:18.569+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:51:18.569+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:51:18.576+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:51:18.574+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_to_snowflake.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-05-20T11:51:18.577+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:51:18.592+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.028 seconds
[2025-05-20T11:51:48.938+0000] {processor.py:157} INFO - Started process (PID=319) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:51:48.938+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T11:51:48.939+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:51:48.939+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:51:48.946+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:51:48.945+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_to_snowflake.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-05-20T11:51:48.946+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:51:48.970+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.035 seconds
[2025-05-20T11:52:19.276+0000] {processor.py:157} INFO - Started process (PID=324) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:52:19.278+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T11:52:19.279+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:52:19.279+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:52:19.297+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:52:19.288+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_to_snowflake.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-05-20T11:52:19.300+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:52:19.325+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.054 seconds
[2025-05-20T11:52:49.555+0000] {processor.py:157} INFO - Started process (PID=329) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:52:49.556+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T11:52:49.558+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:52:49.557+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:52:49.565+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:52:49.563+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_to_snowflake.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-05-20T11:52:49.565+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:52:49.584+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.035 seconds
[2025-05-20T11:53:19.833+0000] {processor.py:157} INFO - Started process (PID=334) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:53:19.835+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T11:53:19.835+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:53:19.835+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:53:19.841+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:53:19.839+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_to_snowflake.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-05-20T11:53:19.841+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:53:19.855+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.025 seconds
[2025-05-20T11:53:50.174+0000] {processor.py:157} INFO - Started process (PID=339) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:53:50.175+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T11:53:50.178+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:53:50.177+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:53:50.189+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:53:50.186+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_to_snowflake.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-05-20T11:53:50.189+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:53:50.216+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.047 seconds
[2025-05-20T11:54:20.571+0000] {processor.py:157} INFO - Started process (PID=344) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:54:20.574+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T11:54:20.576+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:54:20.575+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:54:20.586+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:54:20.584+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_to_snowflake.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-05-20T11:54:20.586+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:54:20.618+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.052 seconds
[2025-05-20T11:54:50.866+0000] {processor.py:157} INFO - Started process (PID=349) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:54:50.868+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T11:54:50.870+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:54:50.869+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:54:50.884+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:54:50.881+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_to_snowflake.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-05-20T11:54:50.884+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:54:50.927+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.067 seconds
[2025-05-20T11:55:21.134+0000] {processor.py:157} INFO - Started process (PID=354) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:55:21.136+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T11:55:21.137+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:55:21.136+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:55:21.145+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:55:21.143+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_to_snowflake.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-05-20T11:55:21.145+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:55:21.179+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.050 seconds
[2025-05-20T11:55:51.430+0000] {processor.py:157} INFO - Started process (PID=359) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:55:51.432+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T11:55:51.433+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:55:51.433+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:55:51.441+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:55:51.440+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_to_snowflake.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-05-20T11:55:51.441+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:55:51.458+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.033 seconds
[2025-05-20T11:56:21.747+0000] {processor.py:157} INFO - Started process (PID=364) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:56:21.750+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T11:56:21.751+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:56:21.751+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:56:21.763+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:56:21.761+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/kafka_to_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_to_snowflake.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-05-20T11:56:21.763+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:56:21.806+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.063 seconds
[2025-05-20T11:56:52.021+0000] {processor.py:157} INFO - Started process (PID=379) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:56:52.023+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T11:56:52.024+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:56:52.024+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:56:53.735+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T11:56:53.904+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:56:54.054+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:56:54.054+0000] {manager.py:499} INFO - Created Permission View: %s
[2025-05-20T11:56:54.059+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:56:54.059+0000] {manager.py:499} INFO - Created Permission View: %s
[2025-05-20T11:56:54.062+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:56:54.062+0000] {manager.py:499} INFO - Created Permission View: %s
[2025-05-20T11:56:54.062+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:56:54.062+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T11:56:54.069+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:56:54.068+0000] {dag.py:2963} INFO - Creating ORM DAG for kafka_to_snowflake
[2025-05-20T11:56:54.074+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:56:54.074+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T10:00:00+00:00, run_after=2025-05-20T11:00:00+00:00
[2025-05-20T11:56:54.084+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 2.067 seconds
[2025-05-20T11:57:24.356+0000] {processor.py:157} INFO - Started process (PID=386) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:57:24.357+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T11:57:24.358+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:57:24.358+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:57:25.106+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T11:57:25.157+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:57:25.189+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:57:25.189+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T11:57:25.203+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:57:25.203+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T10:00:00+00:00, run_after=2025-05-20T11:00:00+00:00
[2025-05-20T11:57:25.213+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.861 seconds
[2025-05-20T11:57:55.547+0000] {processor.py:157} INFO - Started process (PID=393) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:57:55.548+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T11:57:55.549+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:57:55.549+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:57:56.168+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T11:57:56.210+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:57:56.231+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:57:56.231+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T11:57:56.244+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:57:56.244+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T10:00:00+00:00, run_after=2025-05-20T11:00:00+00:00
[2025-05-20T11:57:56.255+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.722 seconds
[2025-05-20T11:58:26.586+0000] {processor.py:157} INFO - Started process (PID=400) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:58:26.587+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T11:58:26.587+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:58:26.587+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:58:27.024+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T11:58:27.059+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:58:27.070+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:58:27.070+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T11:58:27.080+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:58:27.080+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T10:00:00+00:00, run_after=2025-05-20T11:00:00+00:00
[2025-05-20T11:58:27.088+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.505 seconds
[2025-05-20T11:58:57.398+0000] {processor.py:157} INFO - Started process (PID=407) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:58:57.400+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T11:58:57.406+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:58:57.402+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:58:58.069+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T11:58:58.124+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:58:58.145+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:58:58.144+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T11:58:58.158+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:58:58.157+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T10:00:00+00:00, run_after=2025-05-20T11:00:00+00:00
[2025-05-20T11:58:58.168+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.777 seconds
[2025-05-20T11:59:28.397+0000] {processor.py:157} INFO - Started process (PID=414) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:59:28.399+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T11:59:28.400+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:59:28.400+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:59:29.073+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T11:59:29.126+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:59:29.149+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:59:29.149+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T11:59:29.165+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:59:29.165+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T10:00:00+00:00, run_after=2025-05-20T11:00:00+00:00
[2025-05-20T11:59:29.174+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.782 seconds
[2025-05-20T11:59:59.482+0000] {processor.py:157} INFO - Started process (PID=421) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T11:59:59.483+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T11:59:59.484+0000] {logging_mixin.py:154} INFO - [2025-05-20T11:59:59.484+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:00:00.224+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T12:00:00.276+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:00:00.294+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:00:00.294+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T12:00:00.306+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:00:00.306+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T11:00:00+00:00, run_after=2025-05-20T12:00:00+00:00
[2025-05-20T12:00:00.315+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.838 seconds
[2025-05-20T12:00:30.649+0000] {processor.py:157} INFO - Started process (PID=428) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:00:30.650+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T12:00:30.652+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:00:30.651+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:00:31.339+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T12:00:31.380+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:00:31.404+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:00:31.404+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T12:00:31.417+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:00:31.417+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T11:00:00+00:00, run_after=2025-05-20T12:00:00+00:00
[2025-05-20T12:00:31.428+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.784 seconds
[2025-05-20T12:01:01.757+0000] {processor.py:157} INFO - Started process (PID=435) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:01:01.759+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T12:01:01.761+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:01:01.760+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:01:02.392+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T12:01:02.437+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:01:02.455+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:01:02.455+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T12:01:02.467+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:01:02.467+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T11:00:00+00:00, run_after=2025-05-20T12:00:00+00:00
[2025-05-20T12:01:02.475+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.726 seconds
[2025-05-20T12:01:32.805+0000] {processor.py:157} INFO - Started process (PID=442) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:01:32.809+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T12:01:32.810+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:01:32.809+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:01:33.503+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T12:01:33.553+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:01:33.572+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:01:33.571+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T12:01:33.583+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:01:33.583+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T11:00:00+00:00, run_after=2025-05-20T12:00:00+00:00
[2025-05-20T12:01:33.591+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.794 seconds
[2025-05-20T12:02:03.775+0000] {processor.py:157} INFO - Started process (PID=449) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:02:03.775+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T12:02:03.776+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:02:03.776+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:02:04.227+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T12:02:04.271+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:02:04.289+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:02:04.288+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T12:02:04.316+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:02:04.314+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T11:00:00+00:00, run_after=2025-05-20T12:00:00+00:00
[2025-05-20T12:02:04.328+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.557 seconds
[2025-05-20T12:02:34.832+0000] {processor.py:157} INFO - Started process (PID=456) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:02:34.839+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T12:02:34.843+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:02:34.841+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:02:35.504+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T12:02:35.560+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:02:35.595+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:02:35.595+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T12:02:35.608+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:02:35.608+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T11:00:00+00:00, run_after=2025-05-20T12:00:00+00:00
[2025-05-20T12:02:35.618+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.792 seconds
[2025-05-20T12:03:05.981+0000] {processor.py:157} INFO - Started process (PID=463) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:03:05.983+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T12:03:05.985+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:03:05.984+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:03:06.400+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T12:03:06.434+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:03:06.446+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:03:06.446+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T12:03:06.456+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:03:06.456+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T11:00:00+00:00, run_after=2025-05-20T12:00:00+00:00
[2025-05-20T12:03:06.465+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.490 seconds
[2025-05-20T12:03:36.684+0000] {processor.py:157} INFO - Started process (PID=470) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:03:36.685+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T12:03:36.686+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:03:36.686+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:03:37.094+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T12:03:37.132+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:03:37.148+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:03:37.147+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T12:03:37.160+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:03:37.160+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T11:00:00+00:00, run_after=2025-05-20T12:00:00+00:00
[2025-05-20T12:03:37.168+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.488 seconds
[2025-05-20T12:04:07.526+0000] {processor.py:157} INFO - Started process (PID=477) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:04:07.527+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T12:04:07.530+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:04:07.529+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:04:08.021+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T12:04:08.054+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:04:08.065+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:04:08.065+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T12:04:08.075+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:04:08.075+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T11:00:00+00:00, run_after=2025-05-20T12:00:00+00:00
[2025-05-20T12:04:08.083+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.567 seconds
[2025-05-20T12:04:38.260+0000] {processor.py:157} INFO - Started process (PID=484) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:04:38.261+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T12:04:38.263+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:04:38.262+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:04:39.012+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T12:04:39.062+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:04:39.092+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:04:39.092+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T12:04:39.104+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:04:39.104+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T11:00:00+00:00, run_after=2025-05-20T12:00:00+00:00
[2025-05-20T12:04:39.114+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.860 seconds
[2025-05-20T12:05:23.915+0000] {processor.py:157} INFO - Started process (PID=493) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:05:23.917+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T12:05:23.918+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:05:23.918+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:05:24.306+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T12:05:24.340+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:05:24.351+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:05:24.351+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T12:05:24.361+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:05:24.361+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T11:00:00+00:00, run_after=2025-05-20T12:00:00+00:00
[2025-05-20T12:05:24.369+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.459 seconds
[2025-05-20T12:05:57.809+0000] {processor.py:157} INFO - Started process (PID=500) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:05:57.810+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T12:05:57.811+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:05:57.811+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:05:58.309+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T12:05:58.349+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:05:58.367+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:05:58.366+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T12:05:58.380+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:05:58.380+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T11:00:00+00:00, run_after=2025-05-20T12:00:00+00:00
[2025-05-20T12:05:58.389+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.584 seconds
[2025-05-20T12:06:28.765+0000] {processor.py:157} INFO - Started process (PID=507) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:06:28.768+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T12:06:28.770+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:06:28.769+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:06:29.411+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T12:06:29.458+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:06:29.479+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:06:29.478+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T12:06:29.489+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:06:29.489+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T11:00:00+00:00, run_after=2025-05-20T12:00:00+00:00
[2025-05-20T12:06:29.498+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.742 seconds
[2025-05-20T12:07:03.195+0000] {processor.py:157} INFO - Started process (PID=514) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:07:03.197+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T12:07:03.198+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:07:03.197+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:07:03.647+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T12:07:03.684+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:07:03.699+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:07:03.699+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T12:07:03.712+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:07:03.712+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T11:00:00+00:00, run_after=2025-05-20T12:00:00+00:00
[2025-05-20T12:07:03.721+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.531 seconds
[2025-05-20T12:07:33.918+0000] {processor.py:157} INFO - Started process (PID=521) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:07:33.920+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T12:07:33.921+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:07:33.921+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:07:34.519+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T12:07:34.556+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:07:34.570+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:07:34.570+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T12:07:34.582+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:07:34.582+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T11:00:00+00:00, run_after=2025-05-20T12:00:00+00:00
[2025-05-20T12:07:34.591+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.679 seconds
[2025-05-20T12:08:06.971+0000] {processor.py:157} INFO - Started process (PID=528) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:08:06.973+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T12:08:06.975+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:08:06.974+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:08:07.476+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T12:08:07.513+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:08:07.528+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:08:07.528+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T12:08:07.538+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:08:07.538+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T11:00:00+00:00, run_after=2025-05-20T12:00:00+00:00
[2025-05-20T12:08:07.546+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.584 seconds
[2025-05-20T12:08:41.477+0000] {processor.py:157} INFO - Started process (PID=535) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:08:41.479+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T12:08:41.481+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:08:41.480+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:08:42.123+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T12:08:42.179+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:08:42.197+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:08:42.197+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T12:08:42.208+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:08:42.208+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T11:00:00+00:00, run_after=2025-05-20T12:00:00+00:00
[2025-05-20T12:08:42.216+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.748 seconds
[2025-05-20T12:09:12.575+0000] {processor.py:157} INFO - Started process (PID=542) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:09:12.576+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T12:09:12.578+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:09:12.578+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:09:12.932+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T12:09:12.963+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:09:12.975+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:09:12.974+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T12:09:12.984+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:09:12.984+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T11:00:00+00:00, run_after=2025-05-20T12:00:00+00:00
[2025-05-20T12:09:12.992+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.426 seconds
[2025-05-20T12:09:45.134+0000] {processor.py:157} INFO - Started process (PID=549) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:09:45.139+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T12:09:45.141+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:09:45.140+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:09:45.803+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T12:09:45.847+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:09:45.867+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:09:45.866+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T12:09:45.878+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:09:45.878+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T11:00:00+00:00, run_after=2025-05-20T12:00:00+00:00
[2025-05-20T12:09:45.888+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.760 seconds
[2025-05-20T12:10:16.285+0000] {processor.py:157} INFO - Started process (PID=556) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:10:16.286+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T12:10:16.287+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:10:16.287+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:10:16.922+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T12:10:16.965+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:10:17.000+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:10:16.999+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T12:10:17.020+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:10:17.020+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T11:00:00+00:00, run_after=2025-05-20T12:00:00+00:00
[2025-05-20T12:10:17.032+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.750 seconds
[2025-05-20T12:24:57.545+0000] {processor.py:157} INFO - Started process (PID=563) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:24:57.546+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T12:24:57.547+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:24:57.547+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:24:58.369+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T12:24:58.426+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:24:58.449+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:24:58.449+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T12:24:58.465+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:24:58.465+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T11:00:00+00:00, run_after=2025-05-20T12:00:00+00:00
[2025-05-20T12:24:58.478+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.938 seconds
[2025-05-20T12:42:30.742+0000] {processor.py:157} INFO - Started process (PID=572) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:42:30.745+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T12:42:30.748+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:42:30.747+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:42:31.555+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T12:42:31.606+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:42:31.620+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:42:31.619+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T12:42:31.629+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:42:31.629+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T11:00:00+00:00, run_after=2025-05-20T12:00:00+00:00
[2025-05-20T12:42:31.637+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.915 seconds
[2025-05-20T12:43:02.035+0000] {processor.py:157} INFO - Started process (PID=579) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:43:02.040+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T12:43:02.044+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:43:02.043+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:43:02.725+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T12:43:02.768+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:43:02.788+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:43:02.788+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T12:43:02.800+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:43:02.800+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T11:00:00+00:00, run_after=2025-05-20T12:00:00+00:00
[2025-05-20T12:43:02.809+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.781 seconds
[2025-05-20T12:43:33.170+0000] {processor.py:157} INFO - Started process (PID=586) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:43:33.171+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T12:43:33.172+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:43:33.172+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:43:33.517+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T12:43:33.550+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:43:33.562+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:43:33.561+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T12:43:33.573+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:43:33.573+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T11:00:00+00:00, run_after=2025-05-20T12:00:00+00:00
[2025-05-20T12:43:33.581+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.416 seconds
[2025-05-20T12:44:03.679+0000] {processor.py:157} INFO - Started process (PID=593) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:44:03.681+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T12:44:03.683+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:44:03.682+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:44:04.327+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T12:44:04.370+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:44:04.386+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:44:04.386+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T12:44:04.398+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:44:04.398+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T11:00:00+00:00, run_after=2025-05-20T12:00:00+00:00
[2025-05-20T12:44:04.406+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.736 seconds
[2025-05-20T12:44:34.473+0000] {processor.py:157} INFO - Started process (PID=600) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:44:34.474+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T12:44:34.475+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:44:34.474+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:44:34.864+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T12:44:34.895+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:44:34.907+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:44:34.907+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T12:44:34.916+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:44:34.916+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T11:00:00+00:00, run_after=2025-05-20T12:00:00+00:00
[2025-05-20T12:44:34.924+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.456 seconds
[2025-05-20T12:45:05.017+0000] {processor.py:157} INFO - Started process (PID=607) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:45:05.019+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T12:45:05.021+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:45:05.020+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:45:05.589+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T12:45:05.631+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:45:05.649+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:45:05.649+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T12:45:05.661+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:45:05.661+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T11:00:00+00:00, run_after=2025-05-20T12:00:00+00:00
[2025-05-20T12:45:05.669+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.662 seconds
[2025-05-20T12:45:36.022+0000] {processor.py:157} INFO - Started process (PID=614) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:45:36.024+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T12:45:36.025+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:45:36.024+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:45:36.377+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T12:45:36.410+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:45:36.420+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:45:36.420+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T12:45:36.430+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:45:36.430+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T11:00:00+00:00, run_after=2025-05-20T12:00:00+00:00
[2025-05-20T12:45:36.437+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.420 seconds
[2025-05-20T12:46:06.753+0000] {processor.py:157} INFO - Started process (PID=621) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:46:06.755+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T12:46:06.756+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:46:06.756+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:46:07.384+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T12:46:07.427+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:46:07.445+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:46:07.445+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T12:46:07.456+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:46:07.456+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T11:00:00+00:00, run_after=2025-05-20T12:00:00+00:00
[2025-05-20T12:46:07.465+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.722 seconds
[2025-05-20T12:46:37.762+0000] {processor.py:157} INFO - Started process (PID=628) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:46:37.763+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T12:46:37.764+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:46:37.764+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:46:38.183+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T12:46:38.216+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:46:38.227+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:46:38.227+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T12:46:38.238+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:46:38.237+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T11:00:00+00:00, run_after=2025-05-20T12:00:00+00:00
[2025-05-20T12:46:38.245+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.486 seconds
[2025-05-20T12:47:08.304+0000] {processor.py:157} INFO - Started process (PID=635) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:47:08.306+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T12:47:08.307+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:47:08.307+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:47:08.904+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T12:47:08.950+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:47:08.968+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:47:08.968+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T12:47:08.980+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:47:08.980+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T11:00:00+00:00, run_after=2025-05-20T12:00:00+00:00
[2025-05-20T12:47:08.988+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.691 seconds
[2025-05-20T12:47:39.275+0000] {processor.py:157} INFO - Started process (PID=642) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:47:39.277+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T12:47:39.278+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:47:39.277+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:47:39.625+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T12:47:39.655+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:47:39.667+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:47:39.666+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T12:47:39.676+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:47:39.676+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T11:00:00+00:00, run_after=2025-05-20T12:00:00+00:00
[2025-05-20T12:47:39.684+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.413 seconds
[2025-05-20T12:48:10.000+0000] {processor.py:157} INFO - Started process (PID=649) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:48:10.001+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T12:48:10.002+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:48:10.002+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:48:10.665+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T12:48:10.709+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:48:10.725+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:48:10.725+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T12:48:10.736+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:48:10.736+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T11:00:00+00:00, run_after=2025-05-20T12:00:00+00:00
[2025-05-20T12:48:10.744+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.750 seconds
[2025-05-20T12:48:41.011+0000] {processor.py:157} INFO - Started process (PID=656) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:48:41.013+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T12:48:41.014+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:48:41.013+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:48:41.558+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T12:48:41.598+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:48:41.613+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:48:41.613+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T12:48:41.625+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:48:41.625+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T11:00:00+00:00, run_after=2025-05-20T12:00:00+00:00
[2025-05-20T12:48:41.634+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.630 seconds
[2025-05-20T12:49:11.995+0000] {processor.py:157} INFO - Started process (PID=663) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:49:11.998+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T12:49:11.999+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:49:11.998+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:49:12.355+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T12:49:12.386+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:49:12.395+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:49:12.395+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T12:49:12.405+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:49:12.405+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T11:00:00+00:00, run_after=2025-05-20T12:00:00+00:00
[2025-05-20T12:49:12.412+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.429 seconds
[2025-05-20T12:49:42.667+0000] {processor.py:157} INFO - Started process (PID=670) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:49:42.668+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T12:49:42.668+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:49:42.668+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:49:42.996+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T12:49:43.028+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:49:43.042+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:49:43.042+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T12:49:43.054+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:49:43.054+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T11:00:00+00:00, run_after=2025-05-20T12:00:00+00:00
[2025-05-20T12:49:43.063+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.397 seconds
[2025-05-20T12:50:13.382+0000] {processor.py:157} INFO - Started process (PID=677) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:50:13.386+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T12:50:13.389+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:50:13.388+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:50:13.981+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T12:50:14.023+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:50:14.039+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:50:14.039+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T12:50:14.052+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:50:14.052+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T11:00:00+00:00, run_after=2025-05-20T12:00:00+00:00
[2025-05-20T12:50:14.060+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.689 seconds
[2025-05-20T12:50:44.290+0000] {processor.py:157} INFO - Started process (PID=684) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:50:44.291+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T12:50:44.292+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:50:44.292+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:50:44.805+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T12:50:44.849+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T12:50:44.871+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:50:44.871+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T12:50:44.883+0000] {logging_mixin.py:154} INFO - [2025-05-20T12:50:44.883+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T11:00:00+00:00, run_after=2025-05-20T12:00:00+00:00
[2025-05-20T12:50:44.894+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.609 seconds
[2025-05-20T13:06:06.536+0000] {processor.py:157} INFO - Started process (PID=691) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:06:06.537+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:06:06.538+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:06:06.538+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:06:07.269+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:06:07.340+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:06:07.370+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:06:07.370+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:06:07.387+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:06:07.387+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T12:00:00+00:00, run_after=2025-05-20T13:00:00+00:00
[2025-05-20T13:06:07.404+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.875 seconds
[2025-05-20T13:06:37.840+0000] {processor.py:157} INFO - Started process (PID=700) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:06:37.841+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:06:37.842+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:06:37.842+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:06:38.306+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:06:38.337+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:06:38.348+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:06:38.348+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:06:38.358+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:06:38.358+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T12:00:00+00:00, run_after=2025-05-20T13:00:00+00:00
[2025-05-20T13:06:38.366+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.531 seconds
[2025-05-20T13:07:08.414+0000] {processor.py:157} INFO - Started process (PID=707) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:07:08.415+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:07:08.416+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:07:08.416+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:07:08.831+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:07:08.873+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:07:08.888+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:07:08.887+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:07:08.898+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:07:08.898+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T12:00:00+00:00, run_after=2025-05-20T13:00:00+00:00
[2025-05-20T13:07:08.906+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.502 seconds
[2025-05-20T13:07:39.000+0000] {processor.py:157} INFO - Started process (PID=714) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:07:39.002+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:07:39.003+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:07:39.003+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:07:39.405+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:07:39.437+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:07:39.450+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:07:39.449+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:07:39.459+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:07:39.459+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T12:00:00+00:00, run_after=2025-05-20T13:00:00+00:00
[2025-05-20T13:07:39.467+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.476 seconds
[2025-05-20T13:08:09.626+0000] {processor.py:157} INFO - Started process (PID=721) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:08:09.631+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:08:09.633+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:08:09.632+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:08:10.231+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:08:10.271+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:08:10.287+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:08:10.287+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:08:10.297+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:08:10.297+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T12:00:00+00:00, run_after=2025-05-20T13:00:00+00:00
[2025-05-20T13:08:10.305+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.689 seconds
[2025-05-20T13:08:40.678+0000] {processor.py:157} INFO - Started process (PID=728) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:08:40.680+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:08:40.681+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:08:40.681+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:08:41.068+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:08:41.104+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:08:41.115+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:08:41.115+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:08:41.125+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:08:41.125+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T12:00:00+00:00, run_after=2025-05-20T13:00:00+00:00
[2025-05-20T13:08:41.132+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.461 seconds
[2025-05-20T13:09:11.500+0000] {processor.py:157} INFO - Started process (PID=735) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:09:11.503+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:09:11.505+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:09:11.504+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:09:12.090+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:09:12.134+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:09:12.147+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:09:12.147+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:09:12.157+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:09:12.157+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T12:00:00+00:00, run_after=2025-05-20T13:00:00+00:00
[2025-05-20T13:09:12.165+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.673 seconds
[2025-05-20T13:09:42.553+0000] {processor.py:157} INFO - Started process (PID=742) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:09:42.555+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:09:42.556+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:09:42.556+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:09:42.936+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:09:42.969+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:09:42.979+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:09:42.979+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:09:42.989+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:09:42.989+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T12:00:00+00:00, run_after=2025-05-20T13:00:00+00:00
[2025-05-20T13:09:42.996+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.449 seconds
[2025-05-20T13:10:13.116+0000] {processor.py:157} INFO - Started process (PID=749) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:10:13.117+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:10:13.118+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:10:13.118+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:10:13.699+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:10:13.740+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:10:13.755+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:10:13.755+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:10:13.766+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:10:13.766+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T12:00:00+00:00, run_after=2025-05-20T13:00:00+00:00
[2025-05-20T13:10:13.773+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.664 seconds
[2025-05-20T13:10:44.163+0000] {processor.py:157} INFO - Started process (PID=756) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:10:44.164+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:10:44.165+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:10:44.165+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:10:44.570+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:10:44.601+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:10:44.620+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:10:44.619+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:10:44.629+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:10:44.629+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T12:00:00+00:00, run_after=2025-05-20T13:00:00+00:00
[2025-05-20T13:10:44.637+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.479 seconds
[2025-05-20T13:11:14.976+0000] {processor.py:157} INFO - Started process (PID=763) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:11:14.979+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:11:14.981+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:11:14.980+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:11:15.644+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:11:15.690+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:11:15.706+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:11:15.706+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:11:15.717+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:11:15.717+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T12:00:00+00:00, run_after=2025-05-20T13:00:00+00:00
[2025-05-20T13:11:15.725+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.764 seconds
[2025-05-20T13:11:46.119+0000] {processor.py:157} INFO - Started process (PID=770) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:11:46.121+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:11:46.122+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:11:46.121+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:11:46.541+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:11:46.575+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:11:46.587+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:11:46.587+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:11:46.596+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:11:46.596+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T12:00:00+00:00, run_after=2025-05-20T13:00:00+00:00
[2025-05-20T13:11:46.605+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.495 seconds
[2025-05-20T13:21:47.423+0000] {processor.py:157} INFO - Started process (PID=777) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:21:47.424+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:21:47.426+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:21:47.425+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:21:50.798+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:21:50.879+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:21:50.904+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:21:50.903+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:21:50.918+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:21:50.918+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T12:00:00+00:00, run_after=2025-05-20T13:00:00+00:00
[2025-05-20T13:21:50.930+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 3.513 seconds
[2025-05-20T13:22:21.292+0000] {processor.py:157} INFO - Started process (PID=786) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:22:21.297+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:22:21.304+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:22:21.299+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:22:22.110+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:22:22.162+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:22:22.189+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:22:22.189+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:22:22.202+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:22:22.202+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T12:00:00+00:00, run_after=2025-05-20T13:00:00+00:00
[2025-05-20T13:22:22.211+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.925 seconds
[2025-05-20T13:22:52.464+0000] {processor.py:157} INFO - Started process (PID=793) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:22:52.466+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:22:52.467+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:22:52.467+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:22:53.132+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:22:53.180+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:22:53.196+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:22:53.196+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:22:53.207+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:22:53.206+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T12:00:00+00:00, run_after=2025-05-20T13:00:00+00:00
[2025-05-20T13:22:53.215+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.756 seconds
[2025-05-20T13:23:23.634+0000] {processor.py:157} INFO - Started process (PID=800) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:23:23.640+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:23:23.644+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:23:23.643+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:23:24.370+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:23:24.417+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:23:24.430+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:23:24.430+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:23:24.442+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:23:24.441+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T12:00:00+00:00, run_after=2025-05-20T13:00:00+00:00
[2025-05-20T13:23:24.450+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.829 seconds
[2025-05-20T13:23:54.800+0000] {processor.py:157} INFO - Started process (PID=807) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:23:54.804+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:23:54.806+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:23:54.805+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:23:55.453+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:23:55.493+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:23:55.508+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:23:55.508+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:23:55.518+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:23:55.518+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T12:00:00+00:00, run_after=2025-05-20T13:00:00+00:00
[2025-05-20T13:23:55.528+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.736 seconds
[2025-05-20T13:24:25.866+0000] {processor.py:157} INFO - Started process (PID=814) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:24:25.868+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:24:25.869+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:24:25.868+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:24:26.325+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:24:26.359+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:24:26.371+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:24:26.370+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:24:26.381+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:24:26.381+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T12:00:00+00:00, run_after=2025-05-20T13:00:00+00:00
[2025-05-20T13:24:26.389+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.531 seconds
[2025-05-20T13:24:56.442+0000] {processor.py:157} INFO - Started process (PID=821) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:24:56.444+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:24:56.445+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:24:56.444+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:24:57.109+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:24:57.155+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:24:57.171+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:24:57.171+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:24:57.183+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:24:57.183+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T12:00:00+00:00, run_after=2025-05-20T13:00:00+00:00
[2025-05-20T13:24:57.191+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.755 seconds
[2025-05-20T13:25:27.515+0000] {processor.py:157} INFO - Started process (PID=828) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:25:27.517+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:25:27.519+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:25:27.518+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:25:28.035+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:25:28.074+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:25:28.088+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:25:28.088+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:25:28.099+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:25:28.099+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T12:00:00+00:00, run_after=2025-05-20T13:00:00+00:00
[2025-05-20T13:25:28.107+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.600 seconds
[2025-05-20T13:25:58.345+0000] {processor.py:157} INFO - Started process (PID=835) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:25:58.347+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:25:58.348+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:25:58.348+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:25:59.104+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:25:59.154+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:25:59.175+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:25:59.174+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:25:59.187+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:25:59.187+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T12:00:00+00:00, run_after=2025-05-20T13:00:00+00:00
[2025-05-20T13:25:59.203+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.874 seconds
[2025-05-20T13:26:29.517+0000] {processor.py:157} INFO - Started process (PID=842) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:26:29.518+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:26:29.519+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:26:29.519+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:26:30.257+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:26:30.322+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:26:30.347+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:26:30.347+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:26:30.362+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:26:30.362+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T12:00:00+00:00, run_after=2025-05-20T13:00:00+00:00
[2025-05-20T13:26:30.371+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.859 seconds
[2025-05-20T13:27:00.706+0000] {processor.py:157} INFO - Started process (PID=849) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:27:00.707+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:27:00.708+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:27:00.708+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:27:01.078+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:27:01.110+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:27:01.122+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:27:01.122+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:27:01.132+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:27:01.132+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T12:00:00+00:00, run_after=2025-05-20T13:00:00+00:00
[2025-05-20T13:27:01.140+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.440 seconds
[2025-05-20T13:27:31.182+0000] {processor.py:157} INFO - Started process (PID=856) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:27:31.183+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:27:31.184+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:27:31.184+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:27:31.873+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:27:31.925+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:27:31.940+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:27:31.940+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:27:31.952+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:27:31.952+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T12:00:00+00:00, run_after=2025-05-20T13:00:00+00:00
[2025-05-20T13:27:31.960+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.786 seconds
[2025-05-20T13:28:02.312+0000] {processor.py:157} INFO - Started process (PID=863) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:28:02.314+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:28:02.315+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:28:02.315+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:28:02.697+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:28:02.731+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:28:02.748+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:28:02.748+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:28:02.758+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:28:02.758+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T12:00:00+00:00, run_after=2025-05-20T13:00:00+00:00
[2025-05-20T13:28:02.766+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.460 seconds
[2025-05-20T13:28:32.958+0000] {processor.py:157} INFO - Started process (PID=870) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:28:32.961+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:28:32.962+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:28:32.962+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:28:33.604+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:28:33.647+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:28:33.665+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:28:33.664+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:28:33.676+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:28:33.676+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T12:00:00+00:00, run_after=2025-05-20T13:00:00+00:00
[2025-05-20T13:28:33.685+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.735 seconds
[2025-05-20T13:29:04.016+0000] {processor.py:157} INFO - Started process (PID=877) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:29:04.017+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:29:04.018+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:29:04.017+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:29:04.406+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:29:04.438+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:29:04.449+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:29:04.449+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:29:04.459+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:29:04.459+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T12:00:00+00:00, run_after=2025-05-20T13:00:00+00:00
[2025-05-20T13:29:04.467+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.454 seconds
[2025-05-20T13:29:34.556+0000] {processor.py:157} INFO - Started process (PID=884) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:29:34.559+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:29:34.560+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:29:34.559+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:29:35.182+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:29:35.226+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:29:35.242+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:29:35.241+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:29:35.252+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:29:35.252+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T12:00:00+00:00, run_after=2025-05-20T13:00:00+00:00
[2025-05-20T13:29:35.261+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.712 seconds
[2025-05-20T13:30:05.612+0000] {processor.py:157} INFO - Started process (PID=891) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:30:05.617+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:30:05.619+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:30:05.618+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:30:06.190+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:30:06.232+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:30:06.248+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:30:06.248+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:30:06.260+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:30:06.260+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T12:00:00+00:00, run_after=2025-05-20T13:00:00+00:00
[2025-05-20T13:30:06.267+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.671 seconds
[2025-05-20T13:30:36.632+0000] {processor.py:157} INFO - Started process (PID=898) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:30:36.634+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:30:36.635+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:30:36.635+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:30:37.343+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:30:37.390+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:30:37.412+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:30:37.412+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:30:37.424+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:30:37.424+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T12:00:00+00:00, run_after=2025-05-20T13:00:00+00:00
[2025-05-20T13:30:37.432+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.808 seconds
[2025-05-20T13:31:07.795+0000] {processor.py:157} INFO - Started process (PID=905) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:31:07.797+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:31:07.798+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:31:07.797+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:31:08.384+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:31:08.429+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:31:08.446+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:31:08.446+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:31:08.458+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:31:08.458+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T12:00:00+00:00, run_after=2025-05-20T13:00:00+00:00
[2025-05-20T13:31:08.467+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.682 seconds
[2025-05-20T13:31:38.814+0000] {processor.py:157} INFO - Started process (PID=912) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:31:38.816+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:31:38.818+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:31:38.817+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:31:39.540+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:31:39.584+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:31:39.601+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:31:39.601+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:31:39.613+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:31:39.613+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T12:00:00+00:00, run_after=2025-05-20T13:00:00+00:00
[2025-05-20T13:31:39.621+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.817 seconds
[2025-05-20T13:32:09.997+0000] {processor.py:157} INFO - Started process (PID=919) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:32:09.999+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:32:10.000+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:32:10.000+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:32:10.593+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:32:10.633+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:32:10.648+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:32:10.647+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:32:10.659+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:32:10.659+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T12:00:00+00:00, run_after=2025-05-20T13:00:00+00:00
[2025-05-20T13:32:10.667+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.677 seconds
[2025-05-20T13:32:41.047+0000] {processor.py:157} INFO - Started process (PID=926) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:32:41.049+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:32:41.051+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:32:41.050+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:32:41.778+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:32:41.828+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:32:41.861+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:32:41.861+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:32:41.873+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:32:41.873+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T12:00:00+00:00, run_after=2025-05-20T13:00:00+00:00
[2025-05-20T13:32:41.882+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.851 seconds
[2025-05-20T13:33:12.245+0000] {processor.py:157} INFO - Started process (PID=933) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:33:12.248+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:33:12.249+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:33:12.249+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:33:12.841+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:33:12.888+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:33:12.909+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:33:12.909+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:33:12.921+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:33:12.920+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T12:00:00+00:00, run_after=2025-05-20T13:00:00+00:00
[2025-05-20T13:33:12.928+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.688 seconds
[2025-05-20T13:33:43.318+0000] {processor.py:157} INFO - Started process (PID=940) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:33:43.320+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:33:43.322+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:33:43.321+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:33:43.964+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:33:44.009+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:33:44.030+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:33:44.030+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:33:44.041+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:33:44.041+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T12:00:00+00:00, run_after=2025-05-20T13:00:00+00:00
[2025-05-20T13:33:44.050+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.740 seconds
[2025-05-20T13:34:14.414+0000] {processor.py:157} INFO - Started process (PID=951) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:34:14.416+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:34:14.417+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:34:14.417+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:34:14.980+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:34:15.016+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:34:15.033+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:34:15.033+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:34:15.044+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:34:15.044+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T13:00:00+00:00, run_after=2025-05-20T14:00:00+00:00
[2025-05-20T13:34:15.052+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.650 seconds
[2025-05-20T13:34:45.327+0000] {processor.py:157} INFO - Started process (PID=958) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:34:45.329+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:34:45.330+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:34:45.330+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:34:45.900+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:34:45.941+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:34:45.969+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:34:45.968+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:34:45.981+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:34:45.980+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T13:00:00+00:00, run_after=2025-05-20T14:00:00+00:00
[2025-05-20T13:34:45.990+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.667 seconds
[2025-05-20T13:35:16.384+0000] {processor.py:157} INFO - Started process (PID=965) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:35:16.386+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:35:16.388+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:35:16.387+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:35:17.033+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:35:17.085+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:35:17.108+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:35:17.107+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:35:17.122+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:35:17.122+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T13:00:00+00:00, run_after=2025-05-20T14:00:00+00:00
[2025-05-20T13:35:17.132+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.758 seconds
[2025-05-20T13:35:47.469+0000] {processor.py:157} INFO - Started process (PID=972) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:35:47.474+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:35:47.476+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:35:47.475+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:35:48.103+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:35:48.153+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:35:48.177+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:35:48.177+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:35:48.190+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:35:48.190+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T13:00:00+00:00, run_after=2025-05-20T14:00:00+00:00
[2025-05-20T13:35:48.199+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.736 seconds
[2025-05-20T13:36:18.478+0000] {processor.py:157} INFO - Started process (PID=979) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:36:18.481+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:36:18.482+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:36:18.482+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:36:19.134+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:36:19.191+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:36:19.213+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:36:19.213+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:36:19.228+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:36:19.228+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T13:00:00+00:00, run_after=2025-05-20T14:00:00+00:00
[2025-05-20T13:36:19.238+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.774 seconds
[2025-05-20T13:36:49.510+0000] {processor.py:157} INFO - Started process (PID=986) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:36:49.512+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:36:49.514+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:36:49.514+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:36:50.154+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:36:50.212+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:36:50.234+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:36:50.234+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:36:50.248+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:36:50.248+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T13:00:00+00:00, run_after=2025-05-20T14:00:00+00:00
[2025-05-20T13:36:50.257+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.754 seconds
[2025-05-20T13:37:20.580+0000] {processor.py:157} INFO - Started process (PID=993) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:37:20.582+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:37:20.583+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:37:20.583+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:37:21.311+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:37:21.369+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:37:21.395+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:37:21.395+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:37:21.411+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:37:21.411+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T13:00:00+00:00, run_after=2025-05-20T14:00:00+00:00
[2025-05-20T13:37:21.422+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.849 seconds
[2025-05-20T13:37:51.773+0000] {processor.py:157} INFO - Started process (PID=1000) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:37:51.775+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:37:51.777+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:37:51.776+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:37:52.430+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:37:52.471+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:37:52.491+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:37:52.491+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:37:52.505+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:37:52.505+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T13:00:00+00:00, run_after=2025-05-20T14:00:00+00:00
[2025-05-20T13:37:52.514+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.746 seconds
[2025-05-20T13:38:22.918+0000] {processor.py:157} INFO - Started process (PID=1007) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:38:22.920+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:38:22.921+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:38:22.920+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:38:23.593+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:38:23.634+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:38:23.652+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:38:23.652+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:38:23.663+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:38:23.663+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T13:00:00+00:00, run_after=2025-05-20T14:00:00+00:00
[2025-05-20T13:38:23.672+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.763 seconds
[2025-05-20T13:38:54.041+0000] {processor.py:157} INFO - Started process (PID=1014) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:38:54.043+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:38:54.044+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:38:54.044+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:38:54.711+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:38:54.760+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:38:54.783+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:38:54.783+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:38:54.794+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:38:54.794+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T13:00:00+00:00, run_after=2025-05-20T14:00:00+00:00
[2025-05-20T13:38:54.803+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.770 seconds
[2025-05-20T13:39:25.124+0000] {processor.py:157} INFO - Started process (PID=1021) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:39:25.127+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:39:25.128+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:39:25.127+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:39:25.537+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:39:25.570+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:39:25.584+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:39:25.584+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:39:25.596+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:39:25.596+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T13:00:00+00:00, run_after=2025-05-20T14:00:00+00:00
[2025-05-20T13:39:25.604+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.490 seconds
[2025-05-20T13:39:55.863+0000] {processor.py:157} INFO - Started process (PID=1028) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:39:55.864+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:39:55.865+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:39:55.865+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:39:56.413+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:39:56.457+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:39:56.471+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:39:56.471+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:39:56.482+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:39:56.482+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T13:00:00+00:00, run_after=2025-05-20T14:00:00+00:00
[2025-05-20T13:39:56.490+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.631 seconds
[2025-05-20T13:40:26.841+0000] {processor.py:157} INFO - Started process (PID=1035) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:40:26.844+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:40:26.848+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:40:26.846+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:40:27.318+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:40:27.352+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:40:27.364+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:40:27.364+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:40:27.374+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:40:27.374+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T13:00:00+00:00, run_after=2025-05-20T14:00:00+00:00
[2025-05-20T13:40:27.381+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.553 seconds
[2025-05-20T13:40:57.717+0000] {processor.py:157} INFO - Started process (PID=1042) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:40:57.719+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:40:57.721+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:40:57.720+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:40:58.339+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:40:58.388+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:40:58.409+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:40:58.409+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:40:58.424+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:40:58.424+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T13:00:00+00:00, run_after=2025-05-20T14:00:00+00:00
[2025-05-20T13:40:58.433+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.723 seconds
[2025-05-20T13:41:28.744+0000] {processor.py:157} INFO - Started process (PID=1049) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:41:28.746+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:41:28.747+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:41:28.747+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:41:29.461+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:41:29.507+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:41:29.525+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:41:29.524+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:41:29.542+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:41:29.542+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T13:00:00+00:00, run_after=2025-05-20T14:00:00+00:00
[2025-05-20T13:41:29.553+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.821 seconds
[2025-05-20T13:42:00.048+0000] {processor.py:157} INFO - Started process (PID=1056) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:42:00.051+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:42:00.053+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:42:00.052+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:42:00.829+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:42:00.874+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:42:00.902+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:42:00.902+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:42:00.919+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:42:00.919+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T13:00:00+00:00, run_after=2025-05-20T14:00:00+00:00
[2025-05-20T13:42:00.929+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.890 seconds
[2025-05-20T13:42:31.276+0000] {processor.py:157} INFO - Started process (PID=1063) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:42:31.278+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:42:31.281+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:42:31.280+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:42:32.017+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:42:32.074+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:42:32.097+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:42:32.097+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:42:32.118+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:42:32.118+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T13:00:00+00:00, run_after=2025-05-20T14:00:00+00:00
[2025-05-20T13:42:32.135+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.866 seconds
[2025-05-20T13:43:02.495+0000] {processor.py:157} INFO - Started process (PID=1070) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:43:02.498+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:43:02.505+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:43:02.501+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:43:03.130+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:43:03.174+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:43:03.190+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:43:03.190+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:43:03.202+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:43:03.202+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T13:00:00+00:00, run_after=2025-05-20T14:00:00+00:00
[2025-05-20T13:43:03.212+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.723 seconds
[2025-05-20T13:43:33.616+0000] {processor.py:157} INFO - Started process (PID=1086) to work on /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:43:33.617+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/kafka_to_snowflake.py for tasks to queue
[2025-05-20T13:43:33.619+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:43:33.618+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:43:34.209+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T13:43:34.252+0000] {processor.py:839} INFO - DAG(s) dict_keys(['kafka_to_snowflake']) retrieved from /opt/airflow/dags/kafka_to_snowflake.py
[2025-05-20T13:43:34.274+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:43:34.274+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-05-20T13:43:34.287+0000] {logging_mixin.py:154} INFO - [2025-05-20T13:43:34.287+0000] {dag.py:3722} INFO - Setting next_dagrun for kafka_to_snowflake to 2025-05-20T13:00:00+00:00, run_after=2025-05-20T14:00:00+00:00
[2025-05-20T13:43:34.296+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/kafka_to_snowflake.py took 0.685 seconds
